server.port: 8004
#Setting the logging levels for the service
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  contextPath:   /auth

flyway:
  enabled: true
  url: jdbc:postgresql://localhost:5432/auth_service
  user: postgres
  password: root

spring:
  jpa:
    database: "POSTGRESQL"
    show-url: "true"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
  database:
    driverClassName: "org.postgresql.Driver"
  datasource:
    platform:  "postgres"
    url: "jdbc:postgresql://localhost:5432/auth_service"
    driver-class-name: "org.postgresql.Driver"
    username: "postgres"
    password: "root"
    testWhileIdle: "true"
    validationQuery: "SELECT 1"
signing:
  key: "345345fsdfsf5345"